# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev, actions ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.2]

    steps:
    - name: Config repo
      uses: actions/checkout@v2
      with:
        repository: spraakbanken/korp-frontend-sb
        token: ${{ secrets.ACCESS_TOKEN }}
        path: korp-frontend-sb
    - name: Main repo
      uses: actions/checkout@v2
      with:
        path: korp-frontend
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd korp-frontend-sb
        yarn --frozen-lockfile
        cd ../korp-frontend
        yarn --frozen-lockfile
        echo '{"configDir": "../korp-frontend-sb/app"}' > run_config.json
        yarn test
